### PR TITLE
I modified the website and readme

### PR DESCRIPTION
**Pull request by mptorz**
Website will now include a link to my Google Assistant app. It was necessary to change the style and index.html in order to fit a new column. I also mentioned the Google Assistant in a README and added myself as a contributor. 

I wasn't sure if you want me to add my Google Assistant code or just links, so I didn't commited it. Would you like me to add the code of my app to this repository as well?

### CODE REVIEW

**Comment by mptorz** [comment]
After almost two months of waiting Microsoft accepted the Skype bot. I also had some free time so I wrote the kik version and a discord bot that people can add to servers :)

**Comment by estiens** [comment]
@mptorz - I have gotten reports that the discord bot is no longer working or has been removed -- can you let me know?

**Comment by mptorz** [comment]
It is back on now! Tbh. I have no idea what could have caused the downtime. The bot seemed to be offline even though the server was up and running. I restarted my server and now the bot is back online.

**Comment by estiens** [comment]
great thanks!

**Pull request merged**
